using System;
using System.Xml.Serialization;

namespace BroadWorksConnector.Ocip.Models
{
    /// <summary>
    /// Media Stream Type.  Subscriber's media is sent separately from the media generated by the called/calling parties when "Dual" is selected while "Single" is a single media stream that contains all media.
    /// </summary>
    [Serializable]
    [XmlRoot(Namespace = "")]
    public enum MediaStream
    {
        [XmlEnum(Name = "Dual")]
        Dual,
        [XmlEnum(Name = "Single")]
        Single,
    }
}
