using System;
using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations;
using BroadWorksConnector.Ocip.Validation;
using System.Collections.Generic;

namespace BroadWorksConnector.Ocip.Models
{
    /// <summary>
    /// Abstract base type for specifying search criteria. A search criteria is an optional element
    /// used to restrict the number of rows returned when requesting a potentially large set of
    /// data from the provisioning server.
    /// </summary>
    [Serializable]
    [XmlRoot(Namespace = "")]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAccessDeviceEndpointPrivateIdentity))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAccessDeviceVersion))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAdminFirstName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAdminId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAdminLastName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAgentThresholdProfile))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAlternateTrunkIdentity))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAlternateTrunkIdentityDomain))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAlternateUserId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaAnnouncementFileName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaCallCenterName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaCallCenterReportTemplateName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaCallCenterScheduledReportName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaCallParkName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaCallPickupName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaCommunicationBarringAuthorizationCode))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaCommunicationBarringAuthorizationCodeDescription))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDepartmentName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDeviceMACAddress))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDeviceManagementEventAdditionalInfo))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDeviceManagementEventLoginId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDeviceManagementEventRequest))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDeviceManagementEventRequestTrackingId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDeviceName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDeviceNetAddress))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDeviceSerialNumber))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDeviceType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDigitPattern))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDn))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaDomainName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaEmailAddress))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaEnterpriseCommonMultiPartPhoneListName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaEnterpriseCommonPhoneListName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaEnterpriseCommonPhoneListNumber))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaEnterpriseTrunkName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactAnnouncementFileType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactAutoAttendantType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactCallCenterReportTemplateKey))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactCallCenterScheduledReportCreatedBySupervisor))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactCallCenterScheduledReportGroup))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactCallCenterScheduledReportServiceProvider))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactCallCenterType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactCustomContactDirectory))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDeviceLevel))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDeviceManagementEventAction))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDeviceManagementEventLevel))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDeviceManagementEventStatusCompleted))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDeviceManagementEventStatusInProgressOrPending))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDeviceManagementEventType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDeviceServiceProvider))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDeviceType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDeviceTypeConfigurationOptionType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDnActivation))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDnAvailability))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDnDepartment))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactDomainLevel))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactEndpointType21sp1))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactGroupAdminType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactHuntPolicy))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactLocationEnabled))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactMediaFileType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactMobileDnAvailability))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactMobileNetwork))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactOrganizationType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactPolicySelection))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactPortNumber))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactScheduleLevel))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactScheduleType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactServiceProvider))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactServiceProviderAdminType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactServiceType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactSignalingAddressType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactSkillLevel))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactSubscriberType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactUserDepartment))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactUserGroup))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactUserInTrunkGroup))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactUserNetworkClassOfService))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactUserRouteListAssigned))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactUserRouteListAssignment))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactUserType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactVirtualOnNetCallTypeName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExtension))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaForwardedToNumber))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaGroupCommonMultiPartPhoneListName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaGroupCommonPhoneListName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaGroupCommonPhoneListNumber))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaGroupExternalId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaGroupId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaGroupLocationCode))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaGroupName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaHomeMscAddress))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaImpId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaIMRN))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaLanguage))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaLinePortDomain))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaLinePortUserPart))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaLocation))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaLoginId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaMobilePhoneNumber))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaMobileSubscriberDirectoryNumber))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaMultiPartUserName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaNetworkClassOfServiceName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaNumberPortabilityQueryDigitPattern))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaNumberPortabilityStatus))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaOutgoingDNorSIPURI))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaPersonalAssistantExclusionNumber))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaPersonalAssistantExclusionNumberDescription))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaPhysicalLocation))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaReceptionistNote))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaRegistrationURI))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaResellerId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaResellerName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaRoamingMscAddress))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaRoutePointName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaScheduleName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaServiceCode))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaServiceCodeDescription))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaServiceInstanceName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaServiceProviderId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaServiceProviderName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaServiceProviderNumberPortabilityQueryDigitPattern))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaServiceStatus))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaSIPContact))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaSystemServiceDn))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaTitle))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaTrunkGroupName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserExternalId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserFirstName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserHotlineContact))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserLastName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserPersonalMultiPartPhoneListName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserPersonalPhoneListName))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserPersonalPhoneListNumber))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaUserPlaceType))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaYahooId))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaZoneIPAddress))]
    [XmlInclude(typeof(BroadWorksConnector.Ocip.Models.SearchCriteriaExactEndpointType))]

    [Groups(@"[{""__type"":""Sequence:#BroadWorksConnector.Ocip.Validation"",""id"":""972fbf832439609ec8f2765c5637c3f1:50""}]")]
    public abstract class SearchCriteria
    {

    }
}
